# Generated by Django 5.1 on 2024-08-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneNo', models.CharField(max_length=15)),
                ('addressDetails', models.JSONField()),
                ('workExperience', models.JSONField()),
                ('qualifications', models.JSONField()),
                ('projects', models.JSONField()),
                ('photo', models.TextField()),
            ],
        ),
    ]
